### ISSUE TITLE
List of Lapack functions that could benefit

### ISSUE THREAD

**Issue by MichelJuillard** [DynareJulia/FastLapackInterface.jl#1]
- List below the Lapack functions that could benefit of splitting workspace allocation and actual computations
- Record and use the name of original Lapack functions

**Comment by RoyiAvital** [comment]
I'd like to see:

1. Bunch - Kaufman.
2. Cholesky.

This is a great package!

**Comment by MichelJuillard** [comment]
The above functions were added
