### ISSUE TITLE
Resize workspace to smaller system

### ISSUE THREAD

**Issue by jebej** [DynareJulia/FastLapackInterface.jl#22]
Hello,
It seems that at the moment, for the eigen workspaces, a resize is only triggered if the size of the workspace is too small, but not if it is too large:
https://github.com/DynareJulia/FastLapackInterface.jl/blob/e0d766127dec795188402e2d7e75926f73039538/src/eigen.jl#L379

The function therefore returns invalid (too large) arrays for eigenvector and for eigenvalues.

**Comment by louisponet** [comment]
Dear Jebej,

Thank you, you are correct. I will change the behavior so that the right arrays are returned.

**Comment by louisponet** [comment]
I think #23 solved this issue, let me know if you agree! Thanks again for your input it's very valuable

**Comment by jebej** [comment]
I think #25 is still a better fix than the current iteration of #23

**Comment by louisponet** [comment]
Could you be more specific as to why? I'm trying to avoid unnecessary LAPACK calls.

**Comment by jebej** [comment]
I left a comment in #23

**Comment by louisponet** [comment]
Sorry didn't see that one. My notifications are a bit iffy. It's a fair comment though, I'll discuss with @MichelJuillard what he thinks.

**Comment by MichelJuillard** [comment]
I would go with resizing instead of views, so #25 rather than #23, but I wouldn't resize down the Lapack workspace the way #25 is currently doing.

**Comment by louisponet** [comment]
I have removed the views in the last #23 iteration, i.e. now the actual storage for the eigenvalues and vectors are changed/resized, and returned as normal arrays, whereas the work buffers are kept at the larger size.
